import {PST_SUB_ITEMS} from '../../constants/toolbarItems';

describe('PST Syntax Generation', () => {
    it('should generate correct pioneers syntax with visibility ordering', () => {
        const pioneersItem = PST_SUB_ITEMS.find(item => item.id === 'pioneers');
        expect(pioneersItem).toBeDefined();

        if (pioneersItem) {
            // Template call: (maturity1, visibilityHigh, maturity2, visibilityLow)
            const result = pioneersItem.template('0.30', '0.80', '0.70', '0.50');
            expect(result).toBe('pioneers [0.80, 0.30, 0.50, 0.70]');
        }
    });

    it('should generate correct settlers syntax with visibility ordering', () => {
        const settlersItem = PST_SUB_ITEMS.find(item => item.id === 'settlers');
        expect(settlersItem).toBeDefined();

        if (settlersItem) {
            // Template call: (maturity1, visibilityHigh, maturity2, visibilityLow)
            const result = settlersItem.template('0.43', '0.59', '0.63', '0.49');
            expect(result).toBe('settlers [0.59, 0.43, 0.49, 0.63]');
        }
    });

    it('should generate correct townplanners syntax with visibility ordering', () => {
        const townplannersItem = PST_SUB_ITEMS.find(item => item.id === 'townplanners');
        expect(townplannersItem).toBeDefined();

        if (townplannersItem) {
            // Template call: (maturity1, visibilityHigh, maturity2, visibilityLow)
            const result = townplannersItem.template('0.74', '0.31', '0.95', '0.15');
            expect(result).toBe('townplanners [0.31, 0.74, 0.15, 0.95]');
        }
    });

    it('should match the expected syntax format from examples', () => {
        // Test against the examples provided:
        // 'pioneers [0.46, 0.65, 0.59, 0.79]' doesn't display
        // 'pioneers [0.59, 0.65, 0.46, 0.79]' will display
        // This means visibility must be ordered with highest first

        const pioneersItem = PST_SUB_ITEMS.find(item => item.id === 'pioneers');
        expect(pioneersItem).toBeDefined();

        if (pioneersItem) {
            // Working example: [0.59, 0.65, 0.46, 0.79]
            // This means: visibilityHigh=0.59, maturity1=0.65, visibilityLow=0.46, maturity2=0.79
            const workingResult = pioneersItem.template('0.65', '0.59', '0.79', '0.46');
            expect(workingResult).toBe('pioneers [0.59, 0.65, 0.46, 0.79]');

            // Non-working example: [0.46, 0.65, 0.59, 0.79]
            // This would be generated by incorrect ordering
            const nonWorkingResult = pioneersItem.template('0.65', '0.46', '0.79', '0.59');
            expect(nonWorkingResult).toBe('pioneers [0.46, 0.65, 0.59, 0.79]');

            // Verify that our working result has higher visibility first
            expect(0.59).toBeGreaterThan(0.46); // visibilityHigh > visibilityLow
        }
    });

    it('should ensure visibility ordering for proper display', () => {
        // Test that all PST types follow the visibility ordering rule
        const allItems = PST_SUB_ITEMS;

        allItems.forEach(item => {
            // Test with visibilityHigh > visibilityLow
            const result = item.template('0.50', '0.80', '0.70', '0.30');

            // Extract the visibility values from the result
            const match = result.match(/\[(\d+\.\d+), \d+\.\d+, (\d+\.\d+), \d+\.\d+\]/);
            expect(match).toBeTruthy();

            if (match) {
                const visibilityHigh = parseFloat(match[1]);
                const visibilityLow = parseFloat(match[2]);

                // Ensure visibility is ordered correctly (high first, then low)
                expect(visibilityHigh).toBeGreaterThan(visibilityLow);
            }
        });
    });
});
