# frozen_string_literal: true

source "https://rubygems.org"

gem "github-pages", "228", group: :jekyll_plugins
gem 'jekyll', '3.9.3'
gem 'public_suffix', '4.0.7'
gem 'jekyll-sass-converter', '1.5.2'
gem 'webrick'