export const EditorPrefixes = [
	'outsource <component>',
	'build <component>',
	'buy <component>',
	'component',
	'component <name>',
	'component <name> [<visility>, <maturity>]',
	'submap',
	'submap <name>',
	'submap <name> [<visility>, <maturity>]',
	'submap <name> [<visility>, <maturity>] <reference>',
	'anchor',
	'annotation',
	'annotations',
	'style',
	'style wardley',
	'style colour',
	'style handwritten',
	'style plain',
	'evolve',
	'inertia',
	'pipeline',
	'note',
	'note <note text>',
	'note <note text> [<visility>, <maturity>]',
	'title',
	'evolution',
	'y-axis Label->Min->Max',
];
