export const EditorPrefixes = [
	'outsource <component>',
	'build <component>',
	'buy <component>',
	'component',
	'component <name>',
	'component <name> [<visibility>, <maturity>]',
	'submap',
	'submap <name>',
	'submap <name> [<visibility>, <maturity>]',
	'submap <name> [<visibility>, <maturity>] url(<url>)',
	'anchor',
	'annotation',
	'annotations',
	'style',
	'style wardley',
	'style colour',
	'style handwritten',
	'style plain',
	'evolve',
	'inertia',
	'pipeline',
	'note',
	'note <note text>',
	'note <note text> [<visibility>, <maturity>]',
	'url',
	'url <name>',
	'url <name> [<address>]',
	'title',
	'evolution',
	'y-axis Label->Min->Max',
];
